---
- name: Copy the process_exporter systemd service file
  template:
    src: process_exporter.service.j2
    dest: /etc/systemd/system/process_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart process_exporter

- name: Copy configuration file
  copy:
    src: process_exporter_config.yml
    dest: "{{ process_exporter_config_dir }}/config.yml"
    backup: false
    owner: root
    mode: 0644
  notify: restart process_exporter

- name: Allow process_exporter port in SELinux on RedHat OS family
  seport:
    ports: "{{ process_exporter_web_listen_address.split(':')[-1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
